import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import SessionProviders from "@/components/SessionProviders";
import Script from "next/script";



const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Script
        src="https://checkout.razorpay.com/v1/checkout.js"
        strategy="lazyOnload"
      />
        <SessionProviders>{children}</SessionProviders>
      </body>
    </html>
  );
}
